apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  type: Scala
  mode: cluster
  image: sparkacr4c58.azurecr.io/spark-on-aks:stable
  imagePullPolicy: Always
  mainClass: com.microsoftazure.aks.tpcds.DataGenerator
  mainApplicationFile: "local:///opt/spark/jars/tpcdsbenmark_2.12-0.1.0-SNAPSHOT.jar"
  arguments:
    - "abfss://tpcds@tpcds1tb.dfs.core.windows.net/data"
    - "/opt/tpcds-kit/tools"
    - "parquet"
    - "1000"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    envSecretKeyRefs:
      TCPDSDATA_KEY:
        name: tcpdsdata-key
        key: key
    cores: 4
    memory: "8000m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 4
    instances: 12
    memory: "8000m"
    labels:
      version: 3.0.0
