apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  type: Scala
  mode: cluster
  image: sparkacr4c58.azurecr.io/spark-on-aks:stable
  imagePullPolicy: Always
  mainClass: com.microsoftazure.aks.tpcds.TPCDSBenchmark
  mainApplicationFile: "local:///opt/spark/jars/tpcdsbenmark_2.12-0.1.0-SNAPSHOT.jar"
  arguments:
    - 'abfss://tpcds@tpcdsdata.dfs.core.windows.net/data'
    - 'abfss://tpcds@tpcdsdata.dfs.core.windows.net/results'
    - /opt/tpcds-kit/tools
    - parquet
    - '1000'
    - '1'
    - 'false'
    - 'q64-v2.4'
  hadoopConf:
    "spark.sql.shuffle.partitions": "100"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
  - name: "spark-local-dir-1"
    persistentVolumeClaim:
      claimName: azure-managed-disk
  - name: "spark-local-dir-2"
    persistentVolumeClaim:
      claimName: azure-files-premium
  driver:
    envSecretKeyRefs:
      TCPDSDATA_KEY:
        name: tcpdsdata-key
        key: key
    cores: 4
    memory: "8000m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - mountPath: "/tmp/dir1"
        name: "spark-local-dir-1"
    terminationGracePeriodSeconds: 60
  executor:
    cores: 2
    instances: 8
    memory: "8000m"
    labels:
      version: 3.0.0
    volumeMounts:
      - mountPath: "/tmp/dir1"
        name: "spark-local-dir-2"