apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  type: Scala
  mode: cluster
  image: sparkacrfde4.azurecr.io/spark-on-aks:stable
  imagePullPolicy: Always
  env:
    - name: TPCDSDATA-KEY
      valueFrom:
        secretKeyRef:
          name: tcpdsdata-key
          key: key
  mainClass: com.microsoftazure.aks.tpcds.TPCDSBenchmark
  mainApplicationFile: "local:///opt/spark/jars/tpcdsbenmark_2.12-0.1.0-SNAPSHOT.jar"
  arguments:
    - 'abfss://tpcds@tpcdsdata.dfs.core.windows.net/data'
    - 'abfss://tpcds@tpcdsdata.dfs.core.windows.net/results'
    - /opt/tpcds-kit/tools
    - parquet
    - '1000'
    - '1'
    - 'false'
    - 'q64-v2.4'
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
  - name: scratch
    persistentVolumeClaim:
      claimName: azure-managed-disk
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: scratch
        mountPath: /data
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: scratch
        mountPath: /data