apiVersion: v1
kind: Service
metadata:
  name: spark-svc
  labels:
    app: spark
spec:
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: spark
