apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-spark
  labels:
    app: spark
spec:
  selector:
    matchLabels:
      app: spark
  endpoints:
  - port: metrics