# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: "Spark Docker Image"
on:
  push:
    branches:
      - master
    paths:
      - 'spark/**'
  pull_request:
    branches:
      - master
    paths:
      - 'spark/**'
jobs:
  build:
    name: "Docker Build"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./spark/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/spark-on-aks:${{ github.sha }}
      
      - name: 'Push image'
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      - run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spark-on-aks:${{ github.sha }}