# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Docker

on:
  push:
    branches:
      - master
      - release/*
    paths:
    - 'spark/**'
    - '!**/*.md'
  pull_request:
    branches:
      - master
    paths:
    - 'spark/**'
    - '!**/*.md'
jobs:
  docker:
    runs-on: ubuntu-latest
    name: "Docker"

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Download ACR Name
        uses: actions/download-artifact@v1
        with:
          name: drop

      - name: Set Variable
        run: |
          echo ::set-env name=ACR::$(cat drop/acr_name.txt)

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: "${{ env.ACR }}.azurecr.io"
          username: ${{ secrets.CLIENT_ID }}
          password: ${{ secrets.CLIENT_SECRET }}

      - name: Docker Build PR
        if: github.event_name == 'pull_request'
        run: |
          docker build ./spark/ -t ${{ env.ACR }}.azurecr.io/spark-on-aks:${{ github.sha }}

      - name: Docker Build Stable
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker build ./spark/ -t ${{ env.ACR }}.azurecr.io/spark-on-aks:${{ github.sha }} -t ${{ env.ACR }}.azurecr.io/spark-on-aks:stable

      - name: Docker Push Commit
        if: github.event_name == 'pull_request'
        run: |
          docker push ${{ env.ACR }}.azurecr.io/spark-on-aks:${{ github.sha }}

      - name: Docker Push Stable
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker push ${{ env.ACR }}.azurecr.io/spark-on-aks:stable

  aks:
    needs: docker
    runs-on: ubuntu-latest
    name: "Kubernetes"

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Download Drop
        uses: actions/download-artifact@v1
        with:
          name: drop

      - name: Set Variable
        id: vars
        run: |
          echo ::set-output name=AKS::$(cat drop/aks_name.txt)
          echo ::set-output name=AKS_RG::$(cat drop/rg_name.txt)
          echo ::set-output name=ACR::$(cat drop/acr_name.txt)


      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}" # Azure credentials
          resource-group: ${{ steps.vars.outputs.AKS_RG }}
          cluster-name: ${{ steps.vars.outputs.AKS }}

      # Deploy environment via Helm
      - name: 'Install Helm'
        uses: azure/setup-helm@v1
        with:
          version: latest
        id: 'install'

      - name: 'Deploy Helm Charts'
        id: helm-spark
        run: |
          helm repo add loki https://grafana.github.io/loki/charts
          helm repo update
          helm dependency update aks-spark-chart
          helm upgrade --install spark aks-spark-chart --set acr=${{ steps.vars.outputs.ACR }}
          kubectl create secret generic tcpdsdata-key --from-literal=key=${{ secrets.TCPDS_DATA_KEY }}
