# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: "Kubernetes"

on:
  push:
    branches:
      - master
    paths:
      - "kubernetes/**"
  # pull_request:
  #   branches:
  #     - master
  #   paths:
  #     - 'kubernetes/**'
jobs:
  terraform:
    name: "Kubernetes"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}" # Azure credentials
          resource-group: "${{ secrets.AKS_RESOURCE_GROUP }}" # Must be changed if RG name changes
          cluster-name: "${{ secrets.AKS_CLUSTER_NAME }}"

      # Add ACR secrets to cluster
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: "${{ secrets.REGISTRY_LOGIN_SERVER }}"
          container-registry-username: "${{ secrets.REGISTRY_USERNAME }}"
          container-registry-password: "${{ secrets.REGISTRY_PASSWORD }}"
          secret-name: acr

      # Deploy manifests to cluster
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: spark
          manifests: |
            kubernetes/psp-deny-privileged.yaml
            kubernetes/psp-deny-privileged-clusterrole.yaml
            kubernetes/psp-deny-privileged-clusterrolebinding.yaml
            kubernetes/spark-namespace.yaml
            kubernetes/spark-master-service.yaml
            kubernetes/spark-master-controller.yaml
            kubernetes/spark-worker-controller.yaml
