# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: "Kubernetes"

on:
  push:
    branches:
      - master
    paths:
      - 'kubernetes/**'
  # pull_request:
  #   branches:
  #     - master
  #   paths:
  #     - 'kubernetes/**'
jobs:
  terraform:
    name: "Kubernetes"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Azure Kubernetes Service set Context
      - name: AKS Set Context
        uses: Azure/k8s-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resourceGroupName: '${{ secrets.AKS_RESOURCE_GROUP }}' # Must be changed if RG name changes
            clusterName: '${{ secrets.AKS_CLUSTER_NAME }}'
      
      # Add ACR secrets to cluster
      - name: Add ACR Secrets
        uses: Azure/k8s-create-secret@v1
        with:
            container-registry-url: '${{ secrets.REGISTRY_LOGIN_SERVER }}'
            container-registry-username: '${{ secrets.REGISTRY_USERNAME }}'
            container-registry-password: '${{ secrets.REGISTRY_PASSWORD }}'
            secret-name: acr
      
      # Deploy manifests to cluster
      - name: Deploy Kubernetes Manifests
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/spark-namespace.yaml
            kubernetes/spark-role-cluster-role-binding.yaml
            kubernetes/spark-service-account.yaml
